# Autogenerated from websocket_client.template file
import asyncio
import websockets
import json

#This method just sends an arbitrary webSocket message in 'our' format (op and data)
async def send_msg(op, data):
    uri = "ws://127.0.0.1:8888"
    async with websockets.connect(uri) as websocket:
        await websocket.send(json.dumps({"op":op, "data":data}))

        return_val = await websocket.recv()
        #Also, instead of printing the result we return it
        
        return return_val



async def readAll_patient ():
    return await send_msg("readAll_patient", '{""}')

async def add_patient ():
    return await send_msg("add_patient", '{"ssn":"1515151515","name":"Sindri","allergies":"Shellfish"}')

async def delete_patient ():
    return await send_msg("delete_patient", '{"ssn":"1234567890"}')

async def see_patient ():
    return await send_msg("see_patient", '{"id":"" }')

async def see_patient_record ():
    return await send_msg("see_patient_record", '{"id":"" }')

async def add_patient_record ():
    return await send_msg("add_patient_record", '{"ssn":"1515151515", "date":"29/09/2021", "description":"had a dry cough, nothing serious. Gave him some cough syrup" }')

async def add_doctors ():
    return await send_msg("add_doctors", '{"ssn":"2910992629", "name":"aron bergur", "occupation":"surgeon"}')

async def update_doctor ():
    return await send_msg("update_doctor", '{"ssn":"2910992629", "name":"tomas", "occupation":"intern"}')

async def doctor_appointments ():
    return await send_msg("create_appointment", '{"doctor_id":20, "patient_id":20, "date":"2020-12-12", "time":"12:12"}')

async def add_nurses ():
    return await send_msg("add_nurses", '{"nursedetails":"" }')
    
async def get_nurse ():
    return await send_msg("get_nurse", '{"ssn":"1642345642"}')

async def add_drugs_to_inventory():
    return await send_msg("add_drugs_to_inventory", '{"name":"concerta", "quantity": "3", "strength": "200mg", "price": "40" }')

async def view_medical_history ():
    return await send_msg("view_medical_history", '{"id":"" }')

async def order_drugs ():
    return await send_msg("order_drugs", '{"name":"paratabs", "quantity":10, "strength": "500mg" }')

async def view_drug_inventory ():
    return await send_msg("view_drug_inventory", '{ }')

async def create_appointment ():
    return await send_msg("create_appointment", '{"doctor_id":"1111111111", "patient_id":"9999999999", "date":"2022,1,1", "date_time":"0,0,0"')

if __name__ == '__main__':
    #Call each of the generated webSocket methods once and await results.
    print(asyncio.run(readAll_patient()))
    print(asyncio.run(add_patient()))
    print(asyncio.run(add_patient_record()))
    print(asyncio.run(delete_patient()))
    print(asyncio.run(see_patient_record()))
    print(asyncio.run(add_doctors()))
    print(asyncio.run(update_doctor()))
    print(asyncio.run(doctor_appointments()))
    print(asyncio.run(add_nurses()))
    print(asyncio.run(add_drugs_to_inventory()))
    print(asyncio.run(view_medical_history()))
    print(asyncio.run(order_drugs()))
    print(asyncio.run(view_drug_inventory()))
